import { FormEvent, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import worldMapImage from './assets/mapa-mundi-interativo-3d.png'
import { missions, team, type Clue, type CycleEvent, type Intervention, type Mission, type Role } from './data/missions'
import './styles.css'

type Phase = 'investigation' | 'containment' | 'won' | 'lost'
type Modal = 'briefing' | 'reveal' | 'diagnosis' | 'advance' | 'complete' | 'event' | 'wrong' | 'win' | 'lost' | 'feedback' | null
type Student = { name: string; semester: string; focus: string }
type Reveal = Clue | Intervention

const focusLabels: Record<string, string> = { clinica: 'raciocínio clínico', microbiologia: 'microbiologia', epidemiologia: 'epidemiologia', saudeColetiva: 'saúde coletiva' }

function App() {
  const [student, setStudent] = useState<Student | null>(() => { try { return JSON.parse(localStorage.getItem('missao-imunidade-estudante') || 'null') } catch { return null } })
  const [editing, setEditing] = useState(false)
  const [tutorial, setTutorial] = useState(() => localStorage.getItem('missao-imunidade-tutorial-v2') !== 'true')
  const [missionId, setMissionId] = useState<number | null>(null)
  const [completed, setCompleted] = useState<number[]>([])
  const [testMode, setTestMode] = useState(false)
  const [cycle, setCycle] = useState(1)
  const [actions, setActions] = useState(3)
  const [cases, setCases] = useState(0)
  const [clues, setClues] = useState<Clue[]>([])
  const [interventions, setInterventions] = useState<Intervention[]>([])
  const [phase, setPhase] = useState<Phase>('investigation')
  const [modal, setModal] = useState<Modal>(null)
  const [reveal, setReveal] = useState<Reveal | null>(null)
  const [eventOption, setEventOption] = useState<CycleEvent['options'][number] | null>(null)
  const [diagnosis, setDiagnosis] = useState('')
  const [rationale, setRationale] = useState('')
  const [diagnosticError, setDiagnosticError] = useState('')
  useEffect(() => { if (student) localStorage.setItem('missao-imunidade-estudante', JSON.stringify(student)) }, [student])

  const closeTutorial = () => { localStorage.setItem('missao-imunidade-tutorial-v2', 'true'); setTutorial(false) }

  const mission = missions.find((item) => item.id === missionId)
  const foundIds = useMemo(() => new Set(clues.map((item) => item.id)), [clues])
  const interventionIds = useMemo(() => new Set(interventions.map((item) => item.id)), [interventions])
  const start = (item: Mission) => { setMissionId(item.id); setCycle(1); setActions(3); setCases(item.initialCases); setClues([]); setInterventions([]); setPhase('investigation'); setReveal(null); setEventOption(null); setDiagnosis(''); setRationale(''); setModal('briefing') }
  if (!student || editing) return <Profile initial={student || undefined} onSave={(value) => { setStudent(value); setEditing(false) }} />
  if (!mission) return <Campaign student={student} completed={completed} testMode={testMode} tutorial={tutorial} onTutorial={() => setTutorial(true)} onCloseTutorial={closeTutorial} onEdit={() => setEditing(true)} onToggle={() => setTestMode(!testMode)} onStart={start} />

  const inContainment = phase === 'containment'
  const finished = phase === 'won' || phase === 'lost'
  const total = Object.values(mission.clues).flat().length
  const alert = cases < mission.initialCases * 2.5 ? 'Moderado' : cases < mission.initialCases * 7 ? 'Alto' : 'Crítico'
  const requiredComplete = mission.requiredInterventions.every((id) => interventionIds.has(id))
  const cycleEvent = mission.cycleEvents[(cycle - 1) % mission.cycleEvents.length]
  const baseProjected = Math.round(cases * (inContainment ? mission.containmentGrowth : mission.investigationGrowth))
  const projected = eventOption ? Math.round(baseProjected * eventOption.pressureFactor) : baseProjected
  const advance = () => { if (!eventOption) return; const next = projected; setCases(next); setCycle(cycle + 1); setActions(3); setReveal(null); setEventOption(null); setModal(next >= mission.maxCases || cycle >= mission.maxDays ? 'lost' : null); if (next >= mission.maxCases || cycle >= mission.maxDays) setPhase('lost') }
  const closeReveal = () => { setReveal(null); setModal(actions === 0 ? 'complete' : null) }
  const investigate = (role: Role) => { const clue = mission.clues[role].find((item) => !foundIds.has(item.id)); if (!clue || !actions) return; setActions(actions - 1); setClues([...clues, clue]); setReveal(clue); setModal('reveal') }
  const contain = (item: Intervention) => { if (!actions || interventionIds.has(item.id)) return; const next = [...interventions, item]; setActions(actions - 1); setInterventions(next); setCases(Math.max(1, Math.round(cases * item.factor))); if (mission.requiredInterventions.every((id) => next.some((entry) => entry.id === id)) && next.length >= 3) { setPhase('won'); setCompleted(completed.includes(mission.id) ? completed : [...completed, mission.id]); setModal('win') } else { setReveal(item); setModal('reveal') } }
  const confirmDiagnosis = () => { if (!diagnosis || !rationale) return; if (diagnosis === mission.disease && rationale === mission.diagnosticCheck.correctId) { setPhase('containment'); setActions(3); setReveal({ id: 'confirmed', role: 'laboratorio', category: 'Laboratório', level: 2, title: 'Hipótese confirmada', text: 'A etapa agora é responder. Você recebeu três decisões para coordenar medidas proporcionais ao cenário.' }); setModal('reveal'); return } const correctName = diagnosis === mission.disease; setDiagnosticError(correctName ? 'A hipótese foi nomeada corretamente, mas o dado escolhido não é o mais discriminativo. Compare qual evidência separa melhor os diferenciais.' : 'Essa hipótese ainda não explica melhor o conjunto. Retome cronologia, padrão clínico, exposição e laboratório.'); const next = Math.round(cases * mission.investigationGrowth); setCases(next); setCycle(cycle + 1); setActions(3); setModal(next >= mission.maxCases || cycle >= mission.maxDays ? 'lost' : 'wrong'); if (next >= mission.maxCases || cycle >= mission.maxDays) setPhase('lost') }
  const reset = () => start(mission)

  return <main className="game-shell">
    <header className="topbar"><button className="brand brand-button" onClick={() => { setMissionId(null); setModal(null) }}><span className="brand-mark">✦</span><span>MISSÃO <b>IMUNIDADE</b></span></button><div className="mission-chip"><span>{mission.caseCode.toUpperCase()}</span><strong>{mission.shortName}</strong></div><div className="phase-chip"><span>ETAPA</span><strong>{inContainment ? 'Resposta' : phase === 'investigation' ? 'Investigação' : 'Encerrada'}</strong></div><button className="mission-help" onClick={() => setTutorial(true)}>Como jogar</button><div className="day-chip"><span>Ciclo</span><strong>{cycle}</strong></div></header>
    <section className="command-strip"><div className="cycle-state"><span className="pulse-dot" /><div><small>CICLO {cycle} · {inContainment ? 'RESPOSTA' : 'INVESTIGAÇÃO'}</small><strong>{actions} {actions === 1 ? 'decisão restante' : 'decisões restantes'}</strong></div></div><div className="case-state"><span><small>CASOS</small><b>{cases}</b></span><span><small>PRESSÃO</small><b className={`alert ${alert.toLowerCase()}`}>{alert}</b></span></div>{phase === 'investigation' && <button className="diagnose-button" disabled={clues.length < 3} onClick={() => setModal('diagnosis')}>Defender hipótese <small>{clues.length < 3 ? `faltam ${3 - clues.length} evidências` : 'pronto para argumentar'}</small></button>}</section>
    {!finished && <section className="cycle-guide"><div><span>SEU OBJETIVO AGORA</span><b>{inContainment ? 'Aplique 3 medidas, incluindo as 2 essenciais.' : 'Combine lentes diferentes antes de defender uma hipótese.'}</b></div>{actions > 0 && <button onClick={() => setModal('advance')}>Avançar com {actions} decisão{actions > 1 ? 'ões' : ''} não usada{actions > 1 ? 's' : ''}</button>}</section>}
    <section className="dashboard"><div className="map-panel panel"><div className="panel-heading"><div><span className="eyebrow">{mission.caseCode.toUpperCase()} · AGENTE NÃO REVELADO</span><h1>Foco do <em>caso</em></h1></div><span className="live">● ATUALIZADO</span></div><div className="world-map"><img src={worldMapImage} alt="Mapa-múndi ilustrativo" /><div className={`focus-line ${inContainment ? 'contained' : ''}`} style={{ left: `${mission.mapPosition.x}%`, top: `${mission.mapPosition.y}%` }} /><div className={`outbreak-pin ${inContainment ? 'contained' : ''}`} style={{ left: `${mission.mapPosition.x}%`, top: `${mission.mapPosition.y}%` }}><span className="pin-ring" /><span className="pin-core" /><div className="pin-label"><b>{inContainment ? 'RESPOSTA ATIVA' : 'FOCO EM ANÁLISE'}</b><br />{mission.location}</div></div><div className="map-scan" /></div><div className="map-footer"><span>{mission.region} · {mission.location}</span></div></div><Board mission={mission} clues={clues} interventions={interventions} inContainment={inContainment} requiredComplete={requiredComplete} total={total} /></section>
    {phase === 'investigation' && <section className="case-file"><span className="eyebrow">DADOS DISPONÍVEIS AO PLANTÃO</span><h2>{mission.openingSyndrome}</h2><p>{mission.brief}</p><div>{mission.initialData.map((item) => <span key={item.label}>{item.label}<b>{item.value}</b></span>)}</div></section>}
    <section className="team-section"><div className="team-heading"><div><span className="eyebrow">{inContainment ? 'PROTOCOLO DE RESPOSTA' : 'PRÓXIMA DECISÃO'}</span><h2>{inContainment ? 'Escolha uma medida para a resposta' : 'Qual lente você quer investigar?'}</h2></div><div className="action-counter"><b>{actions}</b> decisões neste ciclo</div></div>{phase === 'investigation' && <><p className="choice-intro">Não há resposta certa isolada: compare ao menos duas lentes antes de concluir.</p><div className="team-grid">{team.map((member) => { const roleClues = mission.clues[member.role]; const done = roleClues.filter((clue) => foundIds.has(clue.id)).length; const next = roleClues.find((clue) => !foundIds.has(clue.id)); return <article className={`member-card ${member.tone} ${done === 2 ? 'used' : ''}`} key={member.role}><div className="member-icon">{member.icon}</div><div className="member-info"><span>{member.specialty}</span><h3>{member.name}</h3><p>{next ? `Próximo achado: ${next.title}` : 'Eixo investigado por completo'}</p></div><button onClick={() => investigate(member.role)} disabled={!next || !actions}>{next ? `${member.action} · camada ${done + 1}/2` : 'Eixo concluído'}<span>→</span></button></article> })}</div></>}{inContainment && <div className="team-grid containment-grid">{mission.interventions.map((item) => { const used = interventionIds.has(item.id); const essential = mission.requiredInterventions.includes(item.id); return <article className={`member-card ${item.tone} ${used ? 'used' : ''}`} key={item.id}><div className="member-icon">{item.icon}</div><div className="member-info"><span>{item.label} · {essential ? 'essencial' : 'complementar'}</span><h3>{item.title}</h3><p>{item.text}</p></div><button onClick={() => contain(item)} disabled={used || !actions}>{used ? 'Medida aplicada' : 'Aplicar medida'}<span>→</span></button></article> })}</div>}<div className="mobile-board"><Board mission={mission} clues={clues} interventions={interventions} inContainment={inContainment} requiredComplete={requiredComplete} total={total} /></div>{finished && <div className="finished-actions"><p>{phase === 'won' ? 'Caso concluído. Consulte o debriefing antes de seguir.' : 'A pressão do cenário ultrapassou o limite. Use o debriefing para revisar sua estratégia.'}</p><div><button className="secondary" onClick={() => setModal(phase === 'won' ? 'win' : 'lost')}>Ver debriefing</button><button className="primary" onClick={reset}>Reiniciar caso</button></div></div>}</section>
    <Dialogs modal={modal} mission={mission} cycle={cycle} actions={actions} cases={cases} baseProjected={baseProjected} projected={projected} event={cycleEvent} eventOption={eventOption} clues={clues.length} diagnosis={diagnosis} rationale={rationale} error={diagnosticError} reveal={reveal} outcome={phase === 'won' ? 'vitória' : 'tentativa interrompida'} onClose={() => setModal(null)} onCloseReveal={closeReveal} onSelectDiagnosis={setDiagnosis} onSelectRationale={setRationale} onConfirm={confirmDiagnosis} onShowEvent={() => { setEventOption(null); setModal('event') }} onSelectEventOption={setEventOption} onAdvance={advance} onFeedback={() => setModal('feedback')} onReset={reset} onCampaign={() => { setMissionId(null); setModal(null) }} />
    {tutorial && <Tutorial onClose={closeTutorial} />}
  </main>
}

function Board({ mission, clues, interventions, inContainment, requiredComplete, total }: { mission: Mission; clues: Clue[]; interventions: Intervention[]; inContainment: boolean; requiredComplete: boolean; total: number }) {
  const guidance = clues.length === 0 ? 'Escolha uma lente para registrar o primeiro achado.' : clues.length < 3 ? 'Cruze a descoberta com outro eixo antes de concluir.' : clues.length < 6 ? 'Você já pode defender uma hipótese; investigue mais se ainda houver dúvida.' : 'Seu dossiê está robusto. Pese as evidências.'
  const prompts: Record<number, string> = { 1: 'Qual dado separa uma exposição comum de uma transmissão contínua na comunidade?', 2: 'Que combinação de tempo, lugar e exposição organiza melhor este agrupamento urbano?', 3: 'Como a rede de contatos muda a prioridade da vigilância e da comunicação?', 4: 'Como a duração do quadro reorganiza os diferenciais respiratórios?', 5: 'Por que distinguir colonização de infecção muda a resposta coletiva?' }
  return <aside className="intel-panel panel evidence-board"><div className="intel-heading"><div><span className="eyebrow">QUADRO DO CASO</span><h2>{inContainment ? 'Resposta em andamento' : 'Evidências reunidas'}</h2></div><span>{inContainment ? `${interventions.length}/4` : `${clues.length}/${total}`}</span></div>{!inContainment && <div className="lens-progress">{team.map((member) => { const count = clues.filter((item) => item.role === member.role).length; return <div key={member.role} className={count ? `active ${member.tone}` : ''}><span>{member.icon}</span><b>{count}/2</b><small>{member.specialty.replace('Medicina de ', '')}</small></div> })}</div>}<div className="evidence-list">{!inContainment && !clues.length && <div className="empty-state"><span>⌁</span><p>{guidance}</p></div>}{!inContainment && clues.map((clue) => <article className="evidence-card" key={clue.id}><span>{clue.category} · camada {clue.level}</span><h3>{clue.title}</h3><p>{clue.text}</p></article>)}{inContainment && <div className="response-status"><div className="agent-confirmed">✓ <span>AGENTE CONFIRMADO</span><b>{mission.disease}</b></div><p>Para concluir, aplique três medidas e inclua as duas essenciais.</p>{interventions.map((item) => <article className="evidence-card response-card" key={item.id}><span>{item.label}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div>}</div>{!inContainment && <div className="study-prompt"><span>PERGUNTA PARA DISCUTIR</span><p>{prompts[mission.id]}</p></div>}<div className="hypothesis"><span>{inContainment ? 'OBJETIVO' : 'PRÓXIMO PASSO'}</span><b>{inContainment ? (requiredComplete ? 'Essenciais aplicadas' : 'Priorize as essenciais') : guidance}</b></div></aside>
}

function Dialogs({ modal, mission, cycle, actions, cases, baseProjected, projected, event, eventOption, clues, diagnosis, rationale, error, reveal, outcome, onClose, onCloseReveal, onSelectDiagnosis, onSelectRationale, onConfirm, onShowEvent, onSelectEventOption, onAdvance, onFeedback, onReset, onCampaign }: { modal: Modal; mission: Mission; cycle: number; actions: number; cases: number; baseProjected: number; projected: number; event: CycleEvent; eventOption: CycleEvent['options'][number] | null; clues: number; diagnosis: string; rationale: string; error: string; reveal: Reveal | null; outcome: string; onClose: () => void; onCloseReveal: () => void; onSelectDiagnosis: (value: string) => void; onSelectRationale: (value: string) => void; onConfirm: () => void; onShowEvent: () => void; onSelectEventOption: (value: CycleEvent['options'][number]) => void; onAdvance: () => void; onFeedback: () => void; onReset: () => void; onCampaign: () => void }) {
  if (!modal) return null
  const isClue = reveal && 'category' in reveal
  const score = Math.max(2200, 7000 - (cycle - 1) * 500 - (8 - clues) * 100)
  return <div className="modal-backdrop" role="presentation"><section className={`modal ${modal === 'briefing' ? 'briefing-modal' : ''} ${modal === 'diagnosis' ? 'diagnosis-modal' : ''} ${modal === 'reveal' ? 'reveal-modal' : ''}`} role="dialog" aria-modal="true">
    {modal === 'briefing' && <><span className="modal-kicker">{mission.caseCode.toUpperCase()} · AGENTE OCULTO</span><div className="briefing-icon">⌁</div><h2>{mission.shortName}</h2><p>Cada ciclo tem três decisões. Escolha uma lente, leia o achado e monte o quadro de evidências antes de defender sua hipótese.</p><div className="briefing-case"><b>{mission.openingSyndrome}</b><p>{mission.brief}</p></div><div className="briefing-facts">{mission.initialData.map((item) => <span key={item.label}>{item.label}<b>{item.value}</b></span>)}</div><div className="modal-actions"><button className="primary" onClick={onClose}>Assumir caso</button></div></>}
    {modal === 'reveal' && reveal && <><span className="modal-kicker">{isClue ? `NOVA EVIDÊNCIA · ${(reveal as Clue).category.toUpperCase()}` : 'MEDIDA REGISTRADA'}</span><div className="reveal-symbol">{isClue ? '⌁' : '✓'}</div><h2>{reveal.title}</h2><p className="reveal-text">{reveal.text}</p>{!isClue && (reveal as Intervention).teachingNote && <div className="teaching-note"><span>POR QUE ESTA MEDIDA IMPORTA</span><p>{(reveal as Intervention).teachingNote}</p></div>}<div className="reveal-foot"><span>{actions} {actions === 1 ? 'decisão restante neste ciclo' : 'decisões restantes neste ciclo'}</span><b>{isClue ? 'Adicionado ao Quadro do caso' : 'Resposta atualizada'}</b></div><div className="modal-actions"><button className="primary" onClick={onCloseReveal}>{actions === 0 ? 'Ver fechamento do ciclo' : 'Continuar'}</button></div></>}
    {modal === 'diagnosis' && <><span className="modal-kicker">DEFESA DE HIPÓTESE · {clues} EVIDÊNCIAS</span><h2>Qual hipótese explica melhor o conjunto?</h2><p>Escolha um diferencial e o dado que melhor sustenta sua leitura. Se faltar sustentação, o cenário avança um ciclo.</p><div className="diagnoses">{mission.diagnoses.map((item) => <button className={diagnosis === item ? 'selected' : ''} onClick={() => onSelectDiagnosis(item)} key={item}>{item}</button>)}</div><div className="rationale"><span>{mission.diagnosticCheck.question}</span>{mission.diagnosticCheck.options.map((item) => <button key={item.id} className={rationale === item.id ? 'selected' : ''} onClick={() => onSelectRationale(item.id)}>{item.label}</button>)}</div><div className="modal-actions"><button className="secondary" onClick={onClose}>Voltar ao quadro</button><button className="primary" disabled={!diagnosis || !rationale} onClick={onConfirm}>Defender hipótese</button></div></>}
    {(modal === 'advance' || modal === 'complete') && <><span className="modal-kicker">{modal === 'complete' ? `CICLO ${cycle} CONCLUÍDO` : `AVANÇAR CICLO ${cycle}`}</span><h2>{modal === 'complete' ? 'Hora de observar a evolução do cenário.' : 'Abrir mão de decisões restantes?'}</h2><p>{modal === 'complete' ? 'As três decisões deste ciclo foram usadas. O próximo ciclo traz um sinal operacional que pedirá uma decisão da equipe.' : `Você ainda tem ${actions} decisão${actions > 1 ? 'ões' : ''}. Avançar agora reduz seu tempo de investigação.`}</p><div className="projection"><span>Pressão-base no próximo ciclo</span><b>{cases} → {baseProjected}</b></div><div className="modal-actions">{modal === 'advance' && <button className="secondary" onClick={onClose}>Voltar às decisões</button>}<button className="primary" onClick={onShowEvent}>{modal === 'complete' ? 'Ver situação do próximo ciclo' : 'Avançar mesmo assim'}</button></div></>}
    {modal === 'event' && <><span className="modal-kicker danger-text">SINAL OPERACIONAL · CICLO {cycle + 1}</span><div className="reveal-symbol event-symbol">!</div><h2>{event.title}</h2><p className="reveal-text">{event.text}</p><div className="event-options">{event.options.map((option) => <button className={eventOption?.id === option.id ? 'selected' : ''} onClick={() => onSelectEventOption(option)} key={option.id}><b>{option.label}</b><span>{option.text}</span><small>Pressão adicional: +{Math.round((option.pressureFactor - 1) * 100)}%</small></button>)}</div>{eventOption && <><div className="teaching-note"><span>LEITURA DA ESCOLHA</span><p>{eventOption.teachingNote}</p></div><div className="projection"><span>Casos no próximo ciclo</span><b>{cases} → {projected}</b></div></>}<div className="modal-actions"><button className="primary" disabled={!eventOption} onClick={onAdvance}>Iniciar ciclo {cycle + 1}</button></div></>}
    {modal === 'wrong' && <><span className="modal-kicker danger-text">DEFESA AINDA NÃO SUSTENTADA</span><h2>O caso avançou para o ciclo {cycle}.</h2><p>{error}</p><p className="wrong-note">A pressão aumentou enquanto a equipe reavaliava. Busque uma evidência que diferencie melhor as hipóteses.</p><div className="modal-actions single"><button className="primary" onClick={onClose}>Voltar ao caso</button></div></>}
    {(modal === 'win' || modal === 'lost') && <><div className="trophy">{modal === 'win' ? '🏆' : '⚠️'}</div><span className={`modal-kicker ${modal === 'win' ? 'success-text' : 'danger-text'}`}>{modal === 'win' ? 'RESPOSTA CONCLUÍDA' : 'LIMITE CRÍTICO ATINGIDO'}</span><h2>{modal === 'win' ? `Debriefing: ${mission.disease}` : 'O caso exige uma nova tentativa'}</h2><p>{modal === 'win' ? mission.debrief : 'A pressão do cenário ultrapassou o limite antes de uma resposta adequada. Refaça o caso, cruze lentes de investigação e compare sua decisão com o debriefing educativo.'}</p>{modal === 'win' && <div className="score"><span>SCORE DE RACIOCÍNIO</span><b>{score} pts</b></div>}<div className="learning-box"><span>APRENDIZADOS-CHAVE</span><ul>{mission.learningPoints.map((item) => <li key={item}>{item}</li>)}</ul><a href={mission.source.url} target="_blank" rel="noreferrer">{mission.source.label} ↗</a></div><div className="modal-actions result-actions"><button className="secondary" onClick={onFeedback}>Registrar opinião</button><button className="secondary" onClick={onCampaign}>Central de casos</button><button className="primary" onClick={onReset}>{modal === 'win' ? 'Reabrir caso' : 'Tentar novamente'}</button></div></>}
    {modal === 'feedback' && <FeedbackForm mission={mission} cycle={cycle} outcome={outcome} onClose={onClose} />}
  </section></div>
}

function FeedbackForm({ mission, cycle, outcome, onClose }: { mission: Mission; cycle: number; outcome: string; onClose: () => void }) {
  const [clarity, setClarity] = useState(0); const [engagement, setEngagement] = useState(0); const [reading, setReading] = useState(0); const [comment, setComment] = useState(''); const [saved, setSaved] = useState(false)
  const save = () => { if (!clarity || !engagement || !reading) return; const entry = { mission: mission.caseCode, outcome, cycle, clarity, engagement, reading, comment: comment.trim(), createdAt: new Date().toISOString() }; try { const existing = JSON.parse(localStorage.getItem('missao-imunidade-feedback-v1') || '[]'); localStorage.setItem('missao-imunidade-feedback-v1', JSON.stringify([...existing, entry])); navigator.clipboard?.writeText(`Missão Imunidade — ${mission.caseCode}\nResultado: ${outcome}; ciclo: ${cycle}\nClareza: ${clarity}/5; decisões: ${engagement}/5; leitura: ${reading}/5\nComentário: ${entry.comment || '(sem comentário)'}`); setSaved(true) } catch { setSaved(true) } }
  const scale = (label: string, value: number, setValue: (value: number) => void) => <div className="feedback-scale"><span>{label}</span><div>{[1, 2, 3, 4, 5].map((item) => <button type="button" aria-label={`${label}: ${item} de 5`} className={value === item ? 'selected' : ''} onClick={() => setValue(item)} key={item}>{item}</button>)}</div><small>1 = muito ruim · 5 = muito bom</small></div>
  return <><span className="modal-kicker">TESTE DE EXPERIÊNCIA · OPINIÃO LOCAL</span><h2>Como foi este dossiê?</h2><p>Sua opinião fica somente neste navegador. Ao salvar, um resumo é copiado para você encaminhar à equipe do projeto.</p><div className="feedback-form">{scale('Entendi o ciclo e as consequências?', clarity, setClarity)}{scale('As escolhas pareceram significativas?', engagement, setEngagement)}{scale('A leitura e o celular ficaram confortáveis?', reading, setReading)}<label>O que confundiu, funcionou ou deveria mudar?<textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={700} placeholder="Conte um momento específico do jogo." /></label></div>{saved && <p className="feedback-saved">Opinião salva neste navegador e resumo copiado. Obrigado por testar.</p>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Fechar</button><button className="primary" disabled={!clarity || !engagement || !reading || saved} onClick={save}>{saved ? 'Opinião registrada' : 'Salvar e copiar opinião'}</button></div></>
}

function Profile({ initial, onSave }: { initial?: Student; onSave: (value: Student) => void }) {
  const [name, setName] = useState(initial?.name || ''); const [semester, setSemester] = useState(initial?.semester || '1'); const [focus, setFocus] = useState(initial?.focus || 'clinica'); const [error, setError] = useState('')
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (name.trim().length < 2) { setError('Informe seu nome para personalizar a experiência.'); return } onSave({ name: name.trim(), semester, focus }) }
  return <main className="profile-shell"><section className="profile-card"><div className="profile-mark">✦</div><span className="eyebrow">MISSÃO IMUNIDADE · AMBIENTE DE APRENDIZAGEM</span><h1>Antes do primeiro <em>plantão.</em></h1><p>Monte seu perfil de estudo. Ele adapta a linguagem dos briefings e destaca o eixo que você quer praticar.</p><form onSubmit={submit}><label>Como devemos chamar você?<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Seu nome" maxLength={60} /></label><div className="profile-row"><label>Semestre<select value={semester} onChange={(event) => setSemester(event.target.value)}>{Array.from({ length: 12 }, (_, i) => <option value={String(i + 1)} key={i}>{i + 1}º semestre</option>)}</select></label><label>Eixo de estudo<select value={focus} onChange={(event) => setFocus(event.target.value)}><option value="clinica">Raciocínio clínico</option><option value="microbiologia">Microbiologia</option><option value="epidemiologia">Epidemiologia</option><option value="saudeColetiva">Saúde coletiva</option></select></label></div>{error && <p className="form-error">{error}</p>}<button className="primary">Iniciar dossiês clínicos →</button></form><small>Essas informações ficam somente neste navegador.</small></section></main>
}

function Campaign({ student, completed, testMode, tutorial, onTutorial, onCloseTutorial, onEdit, onToggle, onStart }: { student: Student; completed: number[]; testMode: boolean; tutorial: boolean; onTutorial: () => void; onCloseTutorial: () => void; onEdit: () => void; onToggle: () => void; onStart: (mission: Mission) => void }) {
  const [mapMission, setMapMission] = useState(missions[0]); const first = student.name.split(' ')[0]
  return <main className="campaign-shell"><header className="campaign-header"><div className="brand"><span className="brand-mark">✦</span><span>MISSÃO <b>IMUNIDADE</b></span></div><div className="campaign-account"><button className="help-button" onClick={onTutorial}>Como jogar</button><button onClick={onEdit}>{first} · {student.semester}º semestre</button><button className={`test-toggle ${testMode ? 'active' : ''}`} onClick={onToggle}>{testMode ? 'Modo de teste ativo' : 'Liberar dossiês para teste'}</button></div></header><section className="campaign-hero"><img src={worldMapImage} alt="Mapa-múndi ilustrativo" /><div className="campaign-map-focus" style={{ left: `${mapMission.mapPosition.x}%`, top: `${mapMission.mapPosition.y}%` }}><i /><span><b>{mapMission.caseCode} · {mapMission.shortName}</b>{mapMission.location}</span></div><div className="campaign-hero-copy"><span className="eyebrow">CENTRAL DE INVESTIGAÇÃO</span><h1>Olá, {first}.<br />Vamos ler o <em>surto.</em></h1><p>Escolha um dossiê, investigue por lentes complementares e transforme evidência em resposta.</p><div className="campaign-progress"><b>{completed.length}/5</b><span>concluídos · foco: {focusLabels[student.focus]}</span></div></div></section><section><div className="campaign-title"><div><span className="eyebrow">DOSSIÊS DISPONÍVEIS</span><h2>Onde sua equipe atua agora?</h2></div><p>Toque ou use Tab para localizar o dossiê no mapa e depois assumir o caso.</p></div><div className="mission-grid">{missions.map((mission, index) => { const unlocked = testMode || index === 0 || completed.includes(missions[index - 1].id); const done = completed.includes(mission.id); return <article className={`mission-card ${!unlocked ? 'locked' : ''} ${done ? 'done' : ''} ${mapMission.id === mission.id ? 'map-active' : ''}`} key={mission.id} onMouseEnter={() => setMapMission(mission)} onFocus={() => setMapMission(mission)} onClick={() => setMapMission(mission)}><span className="mission-number">{done ? '✓' : `0${mission.id}`}</span><div className="mission-card-icon">{['🌊', '🦟', '🧭', '🏥', '🧫'][index]}</div><span>{mission.region}</span><h3>{mission.shortName}</h3><p>{mission.openingSyndrome}</p><button disabled={!unlocked} onClick={(event) => { event.stopPropagation(); onStart(mission) }}>{unlocked ? (done ? 'Reabrir dossiê' : 'Assumir caso') : 'Dossiê bloqueado'} <b>→</b></button></article> })}</div></section>{tutorial && <Tutorial onClose={onCloseTutorial} />}</main>
}

function Tutorial({ onClose }: { onClose: () => void }) { return <div className="modal-backdrop tutorial-backdrop"><section className="tutorial tutorial-complete" role="dialog" aria-modal="true" aria-labelledby="tutorial-title"><span className="modal-kicker">GUIA COMPLETO · COMO JOGAR</span><h2 id="tutorial-title">Investigue, decida e explique sua leitura.</h2><p>Missão Imunidade é um jogo de raciocínio em surtos. Você não precisa descobrir o agente por uma pista isolada: a meta é montar uma explicação que conecte clínica, tempo, exposição e exames.</p><div className="tutorial-steps"><article><b>1</b><div><h3>Leia o dossiê e o estado do ciclo</h3><p>Comece pelos dados disponíveis. No topo, veja quantas decisões restam, os casos sob análise e a pressão do cenário. Cada ciclo tem exatamente três decisões.</p></div></article><article><b>2</b><div><h3>Escolha uma lente de investigação</h3><p>Acione emergência para padrão clínico, infectologia para organizar hipóteses, epidemiologia para tempo e exposição, ou laboratório para interpretar exames. Cada lente tem duas camadas.</p></div></article><article><b>3</b><div><h3>Leia o achado antes de continuar</h3><p>A nova evidência abre em destaque e entra no Quadro do caso. Compare-a com outra lente; uma pista forte ganha sentido ao lado do contexto.</p></div></article><article><b>4</b><div><h3>Feche ou avance o ciclo</h3><p>Após três decisões, surge um sinal operacional. Se decidir avançar antes, o jogo informa quantas decisões foram descartadas. A pressão-base e qualquer efeito adicional aparecem antes de serem aplicados.</p></div></article><article><b>5</b><div><h3>Escolha uma resposta para o sinal</h3><p>Eventos oferecem duas ações operacionais. Leia o efeito, a porcentagem de pressão e a justificativa pedagógica. Nenhuma regra fica escondida: a escolha altera o próximo ciclo de forma visível.</p></div></article><article><b>6</b><div><h3>Defenda a hipótese</h3><p>Depois de três evidências, o botão fica disponível. Escolha um diferencial e o dado que melhor o sustenta. Uma defesa ainda insuficiente avança um ciclo e explica onde revisar.</p></div></article><article><b>7</b><div><h3>Coordene a contenção</h3><p>Com a hipótese confirmada, aplique três medidas. Duas são essenciais e aparecem identificadas; as complementares mostram por que também ajudam na resposta.</p></div></article><article><b>8</b><div><h3>Feche o teste</h3><p>No debriefing, reveja os aprendizados e a fonte oficial. Use <strong>Registrar opinião</strong> para avaliar clareza, escolhas e leitura; a resposta fica no navegador e um resumo é copiado para compartilhar com a equipe.</p></div></article></div><div className="tutorial-tip"><b>Estratégia recomendada:</b> nas primeiras decisões, combine pelo menos duas lentes. Antes de defender uma hipótese, pergunte qual dado realmente separa os diferenciais.</div><div className="modal-actions"><button className="primary" onClick={onClose}>Entendi, continuar</button></div></section></div> }

createRoot(document.getElementById('root')!).render(<App />)
